module.exports = (grunt) ->
    require('jit-grunt')(grunt)

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json')

        coffee: {
            default: {
                files: {
                    'router.js': [
                        'src/router.coffee'
                    ]

                    'router_simple.js': [
                        'src/router_simple.coffee'
                    ]
                }
            }
        }

        uglify: {
            dev: {
                options: {
                    mangle: false
                    beautify: true
                    compress: false
                    preserveComments: 'some'
                    banner: '/* AUTOGENERATED DEVELOPMENT CODE */\n'
                }

                files: {
                    'router.js': [
                        'router.js'
                    ]

                    'router_simple.js': [
                        'router_simple.js'
                    ]
                }
            }

            dist: {
                options: {
                    mangle: true
                    beautify: false
                    compress: true
                    preserveComments: 'some'
                    banner: '/* AUTOGENERATED PRODUCTION CODE */\n'
                }

                files: {
                    'router.min.js': [
                        'router.js'
                    ]

                    'router_simple.min.js': [
                        'router_simple.js'
                    ]
                }
            }
        }
    })

    grunt.registerTask('default', [
        'coffee'
        'uglify'
    ])
